# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-16 22:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FootballStats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolsdone',
            name='visualisations',
            field=models.BooleanField(default=False),
        ),
    ]
