# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-18 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FootballStats', '0002_toolsdone_visualisations'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolsdone',
            name='port',
            field=models.BigIntegerField(default=0),
        ),
    ]
