# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-18 16:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FootballStats', '0003_toolsdone_port'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toolsdone',
            name='visualisations',
        ),
        migrations.AddField(
            model_name='file',
            name='visualisations',
            field=models.BooleanField(default=False),
        ),
    ]
